### ISSUE TITLE
CTRL-c exits too gently

### ISSUE THREAD

**Issue by patrickkwang** [maximusunc/AardwolfMUDClient#3]
https://github.com/maximusunc/AardwolfMUDClient/blob/f73638364fc7dbfcf27aa7418d47f3c7e04e84a8/index.js#L99

1. This will fail if you have quest items; it would require `quit quit`
2. Do we want a way to close the connection/client without `quit`ing?

In my mind, `quit` is already the gentle way out. We don't need two ways to do that. So what should CTRL-c do differently?

**Comment by maximusunc** [comment]
This is no longer a thing since we've moved from terminal to electron.
